In [4]:
import numpy as np
import time

In [5]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [6]:
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [8]:
array_1 = np.array([[1, 1], [4, 5], [88, 91]])
array_1

array([[ 1,  1],
       [ 4,  5],
       [88, 91]])

In [13]:
array_1[:,1]


array([ 1,  5, 91])

In [15]:
array_2 = np.add(array_1, 15)
array_2

array([[ 16,  16],
       [ 19,  20],
       [103, 106]])