In [4]:
import numpy as np
import time

In [5]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [6]:
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [8]:
array_1 = np.array([[1, 1], [4, 5], [88, 91]])
array_1

array([[ 1,  1],
       [ 4,  5],
       [88, 91]])

In [13]:
array_1[:,1]


array([ 1,  5, 91])

In [15]:
array_2 = np.add(array_1, 15)
array_2

array([[ 16,  16],
       [ 19,  20],
       [103, 106]])

In [16]:
np.multiply(array_2, 3)

array([[ 48,  48],
       [ 57,  60],
       [309, 318]])

In [17]:
np.transpose(array_2)

array([[ 16,  19, 103],
       [ 16,  20, 106]])

In [18]:
np.invert(array_2)

array([[ -17,  -17],
       [ -20,  -21],
       [-104, -107]])

In [21]:
# now for vectors
vect_1 = np.array([1, 2, 3])
vect_2 = np.array([4, 5, 6])
vect_1
vect_2

array([4, 5, 6])

In [23]:
vect_sum = np.add(vect_1, vect_2)
vect_sum

array([5, 7, 9])

In [24]:
vect_prod = np.multiply(vect_1, vect_2)
vect_prod

array([ 4, 10, 18])

In [25]:
# dot product gives us a scalar
vect_dot = np.dot(vect_1, vect_2)
vect_dot

32

In [26]:
# inverse should fail for singular matrices. i.e., 
array_sing = np.array([[0.5, 0], [0, 0.5]])
np.invert(array_sing)

TypeError: ufunc 'invert' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''