In [6]:
import numpy as np
import time

In [7]:
# create a function that takes a vector and returns a new vector with all elements from the first vector doubled
vect_rand = np.array([1, 2, 3])
vect_doub = np.multiply(vect_rand, 2)
vect_doub

array([2, 4, 6])

In [8]:
# create a function that performs element wise summation on two vectors
vect_1 = np.array([2, 5, 7, 9])
vect_2 = np.array([89, 4, 5, 6])
vect_elSum = np.add(vect_1, vect_2)
vect_elSum


array([91,  9, 12, 15])

In [9]:
# return the dot product of two matrices

matr_1 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
matr_2 = np.array([[9, 8, 7], [6, 5, 4], [3, 2, 1]])
matr_dp = np.dot(matr_1, matr_2)
matr_dp


array([[ 30,  24,  18],
       [ 84,  69,  54],
       [138, 114,  90]])